//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlDataBase.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V5_WinLibs.XmlDataBase.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 在针对对象({0})进行如下操作{1}时发生了异常:{2} 的本地化字符串。
        /// </summary>
        internal static string ChangeActionError {
            get {
                return ResourceManager.GetString("ChangeActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库关闭 的本地化字符串。
        /// </summary>
        internal static string DatabaseClosed {
            get {
                return ResourceManager.GetString("DatabaseClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库启动 的本地化字符串。
        /// </summary>
        internal static string DatabaseOpened {
            get {
                return ResourceManager.GetString("DatabaseOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除了一个对象，编号为{0}, 对象为{1} 的本地化字符串。
        /// </summary>
        internal static string DeleteObject {
            get {
                return ResourceManager.GetString("DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除对象{0}时遇到异常: 该对象不存在或者文件不存在 的本地化字符串。
        /// </summary>
        internal static string DeleteObjectError {
            get {
                return ResourceManager.GetString("DeleteObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库运行期间发生了一般性异常，消息为:{0} 的本地化字符串。
        /// </summary>
        internal static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增了一个对象,编号为:{0},对象为:{1} 的本地化字符串。
        /// </summary>
        internal static string InsertObject {
            get {
                return ResourceManager.GetString("InsertObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进行了对象查询，取得的对象数量是:{0} 的本地化字符串。
        /// </summary>
        internal static string QueryObject {
            get {
                return ResourceManager.GetString("QueryObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成对类型{0}的配置 的本地化字符串。
        /// </summary>
        internal static string TypeConfiguration {
            get {
                return ResourceManager.GetString("TypeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新了一个对象,编号为:{0},对象为:{1} 的本地化字符串。
        /// </summary>
        internal static string UpdateObject {
            get {
                return ResourceManager.GetString("UpdateObject", resourceCulture);
            }
        }
    }
}
